version: '3.8'

services:
  # Sistema centralizado (puerto 5000)
  centralizado:
    build: ./centralizado
    ports:
      - "5000:5000"

  # Sistema distribuido
  servidor:
    build: ./distribuido/servidor
    ports:
      - "5002:5002"

  cliente:
    build: ./distribuido/cliente
    ports:
      - "5003:5003"
    environment:
      - SERVIDOR_URL=http://servidor:5002
    depends_on:
      - servidor
